{% set name = "streamlit-extras" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/arnaudmiribel/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d6e863ab86d251bfb8ffc2abcfcd0fc99583fdc0ba00f4936db51fa0a23766d5
  patches:
  - patch/0001-updating-htbuilder-pinning.patch

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  # s390x is missing streamlit
  skip: true  # [py<38 or s390x]



requirements:
  build:
    - patch       # [not win]
    - m2-patch    # [win]
  host:
    - python
    - poetry-core
    - pip
    - setuptools
    - wheel
  run:
    - python !=3.9.7
    # Only to make conda-build happy... Without this it's not able to see that the package has
    # to be built for all python versions.
    - python
    - entrypoints >=0.4
    - streamlit >=1.0.0
    - st-annotated-text >=3.0.0
    - streamlit-embedcode >=0.1.2
    - streamlit-keyup >=0.1.9
    - protobuf !=3.20.2
    - streamlit-camera-input-live >=0.2.0
    - streamlit-vertical-slider >=2.5.5
    - streamlit-toggle-switch >=1.0.2
    # Temporarily diverging from upstream to fix a conflict that happens in a circular dependency.
    - htbuilder 0.6.1
    - streamlit-faker >=0.0.2
    - streamlit-card >=0.0.4
    - markdownlit >=0.0.5
    - streamlit-image-coordinates >=0.1.1,<1.0.0
    - prometheus_client >=0.14.0
    # upstream forgot to add validators to streamlit-extra 0.4.0, but require validators 0.22.0 for tests.
    # Test pass with validators 0.18.2
    - validators

test:
  source_files:
    - tests
  imports:
    - streamlit_extras
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest
    - pandas

about:
  home: https://share.streamlit.io/
  dev_url: https://github.com/arnaudmiribel/streamlit-extras
  doc_url: https://github.com/arnaudmiribel/streamlit-extras
  summary: A library to discover, try, install and share Streamlit extras
  description: |
    streamlit-extras is a Python library putting together useful Streamlit bits of code (extras).
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache

extra:
  recipe-maintainers:
    - ELundby45
